### ISSUE TITLE
[Ethereum Sample] Implementation

### ISSUE THREAD

**Issue by chloeminkyung** [getdozer/dozer-samples#52]
# Ethereum Sample

- [ ] a tool that monitor exchanges rates across multiple DEXes
- [ ] decode transactions from various DEXes
- [ ] see exchange rates for a pair across different exchangees
- [ ] use dozer to build a decentralized crypto protocol for real time Blockchain analytics

## Todo

- [ ] data source to be used
